# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "noahfrz"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Vulnerability Repair":
        query: 'all:"vulnerability repair" OR all:"vulnerability fixing" OR all:"repairing vulnerabilities" OR all:"security patch generation" OR all:"automated program repair"'
    "Patch Validation":
        query: 'all:"patch validation" OR all:"patch verification" OR all:"patch correctness" OR all:"program repair validation" OR all:"regression test selection"'
